#!/bin/bash
# Apply AI-based categorization to all hierarchy seed files

SEEDS_DIR="/home/nashid/Desktop/study/prephub/backend/src/seeds/hierarchy"

echo "🚀 Applying AI categorization pattern to all hierarchy seeds..."
echo ""

# List of all hierarchy seed files (excluding JavaScript which is already done)
HIERARCHY_SEEDS=(
  "seed-angular-hierarchy.js"
  "seed-api-design-hierarchy.js"
  "seed-aws-cloud-hierarchy.js"
  "seed-c-hierarchy.js"
  "seed-caching-performance-hierarchy.js"
  "seed-code-quality-hierarchy.js"
  "seed-concurrency-hierarchy.js"
  "seed-csharp-hierarchy.js"
  "seed-dart-hierarchy.js"
  "seed-django-hierarchy.js"
  "seed-express-hierarchy.js"
  "seed-flutter-hierarchy.js"
  "seed-git-hierarchy.js"
  "seed-golang-hierarchy.js"
  "seed-html-css-hierarchy.js"
  "seed-java-hierarchy.js"
  "seed-mongodb-hierarchy.js"
  "seed-networking-hierarchy.js"
  "seed-nextjs-hierarchy.js"
  "seed-nodejs-hierarchy.js"
  "seed-os-hierarchy.js"
  "seed-postgresql-hierarchy.js"
  "seed-python-hierarchy.js"
  "seed-react-hierarchy.js"
  "seed-reliability-observability-hierarchy.js"
  "seed-security-engineering-hierarchy.js"
  "seed-system-design-hierarchy.js"
  "seed-typescript-hierarchy.js"
)

echo "📋 Found ${#HIERARCHY_SEEDS[@]} hierarchy seeds to update"
echo "✅ JavaScript already updated"
echo ""
echo "Template: /home/nashid/Desktop/study/prephub/backend/src/seeds/hierarchy/seed-javascript-hierarchy.js"
echo ""
echo "Each file needs:"
echo "  1. Import assignGroupBatch"
echo "  2. Collect category metadata (Step 1)"
echo "  3. Call assignGroupBatch (Step 2)"
echo "  4. Use meta.key for lookup (Step 3)"
echo ""
echo "⚠️  Manual process recommended - each topic has unique structure"
echo ""
echo "Next steps:"
echo "  1. Review JavaScript hierarchy seed as reference"
echo "  2. Apply same 3-step pattern to each file"
echo "  3. Test each topic individually"
echo ""
